package vn.career.auth.infrastructure.security;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.JwtException;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.test.util.ReflectionTestUtils;
import vn.career.auth.domain.Role;
import vn.career.auth.domain.User;
import vn.career.auth.domain.UserStatus;
import vn.career.common.security.AuthenticatedUser;

class JwtServiceTest {

    private static final String SECRET = "unit-test-secret-0123456789-0123456789";
    private static final Instant NOW = Instant.parse("2026-01-01T00:00:00Z");

    private JwtService service(String secret, Instant now) {
        return new JwtService(
                new JwtProperties(secret, "test-issuer", Duration.ofMinutes(15), Duration.ofDays(7)),
                Clock.fixed(now, ZoneOffset.UTC));
    }

    /** Ids are normally generated by Hibernate, so set one directly for these pure unit tests. */
    private static User userWithId(UUID id) {
        User user = User.create("a@example.com", "hash", "A", LocalDate.of(2008, 1, 1),
                Role.STUDENT, UserStatus.ACTIVE);
        ReflectionTestUtils.setField(user, "id", id);
        return user;
    }

    @Test
    void roundTripKeepsIdAndRole() {
        UUID id = UUID.randomUUID();
        JwtService jwt = service(SECRET, NOW);

        AuthenticatedUser parsed = jwt.parse(jwt.generateAccessToken(userWithId(id)));

        assertThat(parsed.id()).isEqualTo(id);
        assertThat(parsed.role()).isEqualTo("STUDENT");
        assertThat(jwt.accessTokenTtlSeconds()).isEqualTo(900);
    }

    @Test
    void expiredTokenIsRejected() {
        String token = service(SECRET, NOW).generateAccessToken(userWithId(UUID.randomUUID()));

        assertThatThrownBy(() -> service(SECRET, NOW.plus(Duration.ofMinutes(16))).parse(token))
                .isInstanceOf(ExpiredJwtException.class);
    }

    @Test
    void tokenSignedWithAnotherKeyIsRejected() {
        String token = service("another-secret-0123456789-0123456789-xx", NOW)
                .generateAccessToken(userWithId(UUID.randomUUID()));

        assertThatThrownBy(() -> service(SECRET, NOW).parse(token)).isInstanceOf(JwtException.class);
    }

    @Test
    void garbageIsRejected() {
        assertThatThrownBy(() -> service(SECRET, NOW).parse("not-a-jwt")).isInstanceOf(JwtException.class);
    }
}
