-- Seed: 30 common majors in Vietnam with their profiles.
--
-- !! The profile weights below are STARTING VALUES derived from Holland's RIASEC theory and general reading about
-- !! each field. They are NOT validated data and MUST be reviewed by a career-guidance expert before real use.
--
-- Weight order: R I A S E C | LOGIC VERBAL SPATIAL SOCIAL_SKILL CREATIVE NUMERIC |
--               VAL_INCOME VAL_STABILITY VAL_HELPING VAL_CREATIVITY VAL_AUTONOMY VAL_PRESTIGE VAL_TEAMWORK

CREATE TEMP TABLE seed_majors (
    code              TEXT, name TEXT, group_name TEXT, short_description TEXT, description TEXT,
    combos            TEXT[], typical_jobs TEXT[], profile NUMERIC[]
) ON COMMIT DROP;

INSERT INTO seed_majors VALUES
('IT', 'Công nghệ thông tin', 'Công nghệ thông tin',
 'Thiết kế, xây dựng và vận hành phần mềm, hệ thống và ứng dụng.',
 'Ngành đào tạo kiến thức về lập trình, cấu trúc dữ liệu, cơ sở dữ liệu, mạng và kỹ nghệ phần mềm. Người học thường xuyên giải quyết vấn đề bằng tư duy logic và làm việc theo dự án.',
 ARRAY['A00','A01','D01'], ARRAY['Lập trình viên','Kỹ sư kiểm thử phần mềm','Quản trị hệ thống','Lập trình ứng dụng di động'],
 ARRAY[.6,.9,.3,.2,.3,.5, 1,.4,.5,.3,.5,.8, .8,.5,.2,.6,.6,.4,.5]),
('DS', 'Khoa học dữ liệu', 'Công nghệ thông tin',
 'Thu thập, phân tích dữ liệu và xây dựng mô hình dự báo để hỗ trợ ra quyết định.',
 'Kết hợp toán, thống kê và lập trình để rút ra thông tin từ dữ liệu lớn. Người học làm quen với học máy, trực quan hóa dữ liệu và xử lý dữ liệu.',
 ARRAY['A00','A01','D01'], ARRAY['Chuyên viên phân tích dữ liệu','Kỹ sư dữ liệu','Nhà khoa học dữ liệu'],
 ARRAY[.3,.9,.2,.1,.3,.6, 1,.4,.3,.2,.4,1, .8,.6,.2,.5,.5,.5,.5]),
('CYBERSEC', 'An toàn thông tin', 'Công nghệ thông tin',
 'Bảo vệ hệ thống, mạng và dữ liệu trước các cuộc tấn công.',
 'Đào tạo về mật mã, an ninh mạng, kiểm thử xâm nhập và quản trị rủi ro thông tin. Phù hợp với người tỉ mỉ, thích tìm lỗi và hiểu sâu cách hệ thống hoạt động.',
 ARRAY['A00','A01','D01'], ARRAY['Chuyên viên an ninh mạng','Kiểm thử xâm nhập','Chuyên viên ứng cứu sự cố'],
 ARRAY[.6,.9,.1,.1,.2,.6, 1,.3,.3,.2,.5,.8, .8,.6,.3,.4,.6,.5,.4]),
('ECOMMERCE', 'Thương mại điện tử', 'Kinh tế - Kinh doanh',
 'Xây dựng và vận hành hoạt động kinh doanh trên nền tảng số.',
 'Kết hợp kiến thức kinh doanh, marketing số và công nghệ để vận hành sàn thương mại, cửa hàng trực tuyến và chuỗi cung ứng số.',
 ARRAY['A00','A01','D01'], ARRAY['Chuyên viên vận hành sàn thương mại điện tử','Chuyên viên marketing số','Quản lý cửa hàng trực tuyến'],
 ARRAY[.2,.5,.4,.3,.8,.5, .6,.5,.3,.5,.6,.7, .8,.4,.1,.6,.6,.5,.5]),
('ACCOUNTING', 'Kế toán', 'Kinh tế - Kinh doanh',
 'Ghi chép, tổng hợp và kiểm soát thông tin tài chính của tổ chức.',
 'Đào tạo nguyên lý kế toán, kế toán tài chính, thuế và kiểm toán. Công việc đòi hỏi cẩn thận, chính xác và tuân thủ quy định.',
 ARRAY['A00','A01','D01'], ARRAY['Kế toán viên','Kiểm toán viên','Chuyên viên thuế'],
 ARRAY[.1,.4,.1,.2,.3,.9, .6,.4,.1,.3,.1,1, .5,.9,.2,.1,.2,.4,.5]),
('MARKETING', 'Marketing', 'Kinh tế - Kinh doanh',
 'Nghiên cứu khách hàng, xây dựng thương hiệu và thúc đẩy bán hàng.',
 'Người học nghiên cứu thị trường, hành vi tiêu dùng, truyền thông thương hiệu và marketing số. Cần sáng tạo, giao tiếp tốt và nhạy bén với xu hướng.',
 ARRAY['A00','A01','D01','D07'], ARRAY['Chuyên viên marketing','Quản lý thương hiệu','Chuyên viên nghiên cứu thị trường'],
 ARRAY[0,.3,.6,.5,.9,.3, .4,.8,.2,.8,.9,.5, .7,.4,.2,.8,.5,.5,.7]),
('BUSINESS', 'Quản trị kinh doanh', 'Kinh tế - Kinh doanh',
 'Lập kế hoạch, tổ chức và điều hành hoạt động của doanh nghiệp.',
 'Trang bị kiến thức quản trị, tài chính, nhân sự và chiến lược. Phù hợp với người thích lãnh đạo, giao tiếp và ra quyết định.',
 ARRAY['A00','A01','D01'], ARRAY['Quản lý bộ phận','Chuyên viên kinh doanh','Khởi nghiệp'],
 ARRAY[.1,.4,.3,.5,.9,.6, .6,.7,.2,.8,.6,.6, .8,.5,.3,.5,.6,.7,.7]),
('FINANCE', 'Tài chính - Ngân hàng', 'Kinh tế - Kinh doanh',
 'Quản lý dòng tiền, đầu tư, tín dụng và dịch vụ tài chính.',
 'Người học tìm hiểu thị trường tài chính, ngân hàng thương mại, quản trị rủi ro và phân tích đầu tư. Đòi hỏi tư duy số liệu tốt và tính chính trực.',
 ARRAY['A00','A01','D01'], ARRAY['Chuyên viên tín dụng','Chuyên viên phân tích đầu tư','Giao dịch viên ngân hàng'],
 ARRAY[0,.5,0,.3,.7,.8, .7,.5,.1,.5,.2,1, .9,.8,.1,.2,.3,.8,.5]),
('INTLECON', 'Kinh tế quốc tế', 'Kinh tế - Kinh doanh',
 'Nghiên cứu thương mại, đầu tư và quan hệ kinh tế giữa các quốc gia.',
 'Kết hợp kinh tế học, ngoại thương và ngoại ngữ. Người học chuẩn bị cho công việc trong doanh nghiệp xuất nhập khẩu, tổ chức quốc tế.',
 ARRAY['A00','A01','D01','D07'], ARRAY['Chuyên viên xuất nhập khẩu','Chuyên viên phân tích kinh tế','Nhân viên ngoại thương'],
 ARRAY[0,.6,.2,.5,.7,.6, .6,.8,.1,.7,.4,.7, .8,.5,.2,.4,.5,.7,.6]),
('LOGISTICS', 'Logistics và quản lý chuỗi cung ứng', 'Kinh tế - Kinh doanh',
 'Tổ chức vận chuyển, kho bãi và dòng hàng hóa từ nhà sản xuất đến khách hàng.',
 'Đào tạo về quản lý chuỗi cung ứng, vận tải, kho vận và thương mại quốc tế. Phù hợp với người thích tổ chức và tối ưu quy trình.',
 ARRAY['A00','A01','D01'], ARRAY['Chuyên viên logistics','Điều phối vận tải','Quản lý kho'],
 ARRAY[.4,.4,0,.3,.6,.7, .7,.5,.5,.5,.3,.7, .6,.7,.2,.2,.3,.4,.7]),
('MEDICINE', 'Y đa khoa', 'Y - Dược - Sức khỏe',
 'Khám, chẩn đoán, điều trị và phòng bệnh cho con người.',
 'Chương trình đào tạo dài, kết hợp khoa học cơ bản, y học lâm sàng và thực hành tại bệnh viện. Đòi hỏi sức bền, trách nhiệm và tinh thần giúp đỡ người bệnh.',
 ARRAY['B00'], ARRAY['Bác sĩ đa khoa','Bác sĩ chuyên khoa','Nghiên cứu y học'],
 ARRAY[.5,.8,.1,.8,.2,.4, .7,.5,.5,.7,.2,.5, .7,.8,1,.2,.3,.9,.7]),
('NURSING', 'Điều dưỡng', 'Y - Dược - Sức khỏe',
 'Chăm sóc, theo dõi và hỗ trợ người bệnh trong quá trình điều trị.',
 'Đào tạo kỹ năng chăm sóc người bệnh, thực hành lâm sàng và giao tiếp với bệnh nhân. Phù hợp với người kiên nhẫn và giàu đồng cảm.',
 ARRAY['B00','D08'], ARRAY['Điều dưỡng viên','Điều dưỡng trưởng','Chăm sóc sức khỏe tại nhà'],
 ARRAY[.5,.5,.1,.9,.1,.5, .4,.5,.2,.9,.1,.3, .4,.8,1,.1,.2,.4,.9]),
('PHARMACY', 'Dược học', 'Y - Dược - Sức khỏe',
 'Nghiên cứu, sản xuất, kiểm nghiệm và tư vấn sử dụng thuốc.',
 'Người học tìm hiểu hóa dược, dược lý, bào chế và quản lý dược. Công việc chính xác, đòi hỏi kiến thức khoa học vững.',
 ARRAY['A00','B00','D07'], ARRAY['Dược sĩ','Chuyên viên kiểm nghiệm thuốc','Trình dược viên'],
 ARRAY[.5,.8,0,.5,.2,.6, .7,.5,.3,.5,.3,.7, .6,.8,.7,.2,.3,.6,.6]),
('BIOTECH', 'Công nghệ sinh học', 'Khoa học - Công nghệ',
 'Ứng dụng sinh học vào y học, nông nghiệp, thực phẩm và môi trường.',
 'Kết hợp sinh học phân tử, hóa sinh và công nghệ để tạo ra sản phẩm sinh học. Nhiều thời gian làm việc trong phòng thí nghiệm.',
 ARRAY['A00','B00','D07','D08'], ARRAY['Nghiên cứu viên phòng thí nghiệm','Kỹ thuật viên sinh học','Chuyên viên kiểm định chất lượng'],
 ARRAY[.6,1,.1,.2,.1,.4, .8,.4,.4,.2,.5,.6, .5,.6,.5,.6,.5,.5,.6]),
('FOODTECH', 'Công nghệ thực phẩm', 'Khoa học - Công nghệ',
 'Nghiên cứu, chế biến và kiểm soát chất lượng thực phẩm.',
 'Đào tạo về hóa học thực phẩm, vi sinh, quy trình chế biến và an toàn thực phẩm.',
 ARRAY['A00','B00','D07'], ARRAY['Kỹ sư chế biến thực phẩm','Chuyên viên kiểm soát chất lượng','Nghiên cứu sản phẩm mới'],
 ARRAY[.7,.7,.1,.1,.2,.6, .6,.3,.3,.3,.4,.5, .5,.7,.3,.3,.3,.3,.6]),
('LAW', 'Luật', 'Khoa học xã hội',
 'Nghiên cứu, áp dụng và tư vấn về pháp luật.',
 'Người học nắm hệ thống pháp luật, kỹ năng lập luận, soạn thảo văn bản và tranh tụng. Đòi hỏi đọc nhiều, tư duy chặt chẽ và diễn đạt tốt.',
 ARRAY['A00','C00','D01'], ARRAY['Luật sư','Pháp chế doanh nghiệp','Thẩm phán, kiểm sát viên'],
 ARRAY[0,.6,.2,.5,.7,.6, .8,1,.1,.7,.3,.2, .7,.6,.6,.2,.5,.8,.4]),
('PSYCHOLOGY', 'Tâm lý học', 'Khoa học xã hội',
 'Tìm hiểu hành vi, cảm xúc và tư duy của con người để hỗ trợ và tư vấn.',
 'Người học nghiên cứu tâm lý phát triển, tâm lý xã hội, trắc nghiệm và tham vấn. Cần lắng nghe tốt và tôn trọng đạo đức nghề nghiệp.',
 ARRAY['B00','C00','D01'], ARRAY['Chuyên viên tham vấn học đường','Chuyên viên nhân sự','Nghiên cứu tâm lý'],
 ARRAY[0,.8,.3,.8,.3,.3, .6,.8,.1,1,.4,.4, .4,.5,1,.4,.5,.5,.6]),
('SOCIALWORK', 'Công tác xã hội', 'Khoa học xã hội',
 'Hỗ trợ cá nhân, gia đình và cộng đồng giải quyết khó khăn.',
 'Đào tạo kỹ năng làm việc với nhóm yếu thế, tổ chức hoạt động cộng đồng và kết nối nguồn lực.',
 ARRAY['C00','C03','D01'], ARRAY['Nhân viên công tác xã hội','Điều phối viên dự án cộng đồng','Cán bộ tổ chức phi chính phủ'],
 ARRAY[.1,.4,.3,1,.4,.4, .3,.7,.1,1,.3,.2, .2,.5,1,.3,.4,.3,.8]),
('EDUCATION', 'Sư phạm', 'Sư phạm',
 'Đào tạo giáo viên các cấp học.',
 'Người học được trang bị chuyên môn, phương pháp giảng dạy và kỹ năng quản lý lớp học. Phù hợp với người kiên nhẫn, thích chia sẻ kiến thức.',
 ARRAY['A00','C00','D01'], ARRAY['Giáo viên','Giảng viên','Chuyên viên giáo dục'],
 ARRAY[.1,.5,.4,.9,.3,.5, .5,.8,.2,.9,.5,.4, .3,.9,.9,.5,.4,.5,.7]),
('ENGLISH', 'Ngôn ngữ Anh', 'Ngôn ngữ - Truyền thông',
 'Đào tạo sử dụng tiếng Anh thành thạo và hiểu biết về văn hóa, ngôn ngữ.',
 'Người học phát triển bốn kỹ năng nghe, nói, đọc, viết cùng biên phiên dịch và giao tiếp liên văn hóa.',
 ARRAY['D01','D14','D15'], ARRAY['Biên dịch, phiên dịch','Giáo viên tiếng Anh','Nhân viên đối ngoại'],
 ARRAY[0,.5,.6,.6,.5,.4, .4,1,.1,.8,.6,.2, .5,.5,.4,.5,.5,.4,.6]),
('JOURNALISM', 'Báo chí', 'Ngôn ngữ - Truyền thông',
 'Thu thập thông tin, viết bài và sản xuất nội dung báo chí.',
 'Đào tạo kỹ năng viết, phỏng vấn, biên tập và sản xuất nội dung đa phương tiện. Cần tò mò, nhạy bén và chịu được áp lực thời gian.',
 ARRAY['C00','D01','D14','D15'], ARRAY['Phóng viên','Biên tập viên','Người sản xuất nội dung'],
 ARRAY[0,.6,.7,.6,.6,.3, .5,1,.2,.8,.8,.2, .4,.4,.6,.8,.7,.6,.5]),
('PR', 'Quan hệ công chúng', 'Ngôn ngữ - Truyền thông',
 'Xây dựng hình ảnh và quản lý truyền thông cho tổ chức.',
 'Người học tìm hiểu truyền thông, tổ chức sự kiện, quản trị khủng hoảng và quan hệ báo chí.',
 ARRAY['A01','C00','D01','D14'], ARRAY['Chuyên viên quan hệ công chúng','Tổ chức sự kiện','Chuyên viên truyền thông nội bộ'],
 ARRAY[0,.2,.6,.7,.8,.3, .4,.9,.2,1,.8,.3, .6,.4,.3,.7,.5,.6,.7]),
('MULTIMEDIA', 'Truyền thông đa phương tiện', 'Ngôn ngữ - Truyền thông',
 'Sản xuất nội dung số: hình ảnh, video, âm thanh, web và mạng xã hội.',
 'Kết hợp thiết kế, kể chuyện và công nghệ để tạo sản phẩm truyền thông trên nhiều nền tảng.',
 ARRAY['A00','A01','D01'], ARRAY['Nhà sản xuất video','Chuyên viên sáng tạo nội dung','Thiết kế web, đồ họa chuyển động'],
 ARRAY[.3,.3,.9,.4,.5,.2, .3,.6,.6,.6,1,.2, .5,.3,.2,1,.7,.4,.7]),
('GRAPHICDESIGN', 'Thiết kế đồ họa', 'Nghệ thuật - Thiết kế',
 'Sáng tạo hình ảnh trực quan cho thương hiệu, ấn phẩm và sản phẩm số.',
 'Người học rèn luyện thẩm mỹ, bố cục, màu sắc, phần mềm thiết kế và tư duy sáng tạo hình ảnh.',
 ARRAY['A00','A01','D01'], ARRAY['Nhà thiết kế đồ họa','Họa sĩ minh họa','Thiết kế giao diện'],
 ARRAY[.3,.3,1,.2,.3,.2, .3,.4,.9,.4,1,.2, .5,.3,.2,1,.8,.3,.5]),
('ARCHITECTURE', 'Kiến trúc', 'Nghệ thuật - Thiết kế',
 'Thiết kế công trình và không gian sống, làm việc.',
 'Kết hợp mỹ thuật, kỹ thuật và tư duy không gian. Người học thực hiện nhiều đồ án thiết kế và bản vẽ.',
 ARRAY['A00','A01','D01'], ARRAY['Kiến trúc sư','Thiết kế nội thất','Quy hoạch đô thị'],
 ARRAY[.6,.5,.8,.2,.3,.4, .6,.3,1,.4,.9,.6, .6,.5,.3,.9,.6,.6,.6]),
('MECHANICAL', 'Kỹ thuật cơ khí', 'Kỹ thuật',
 'Thiết kế, chế tạo và vận hành máy móc, thiết bị.',
 'Đào tạo về cơ học, vật liệu, thiết kế máy và tự động hóa. Người học thường làm việc với bản vẽ kỹ thuật và xưởng thực hành.',
 ARRAY['A00','A01','D07'], ARRAY['Kỹ sư cơ khí','Kỹ sư thiết kế','Kỹ sư bảo trì'],
 ARRAY[1,.6,.2,.1,.2,.5, .8,.2,.9,.2,.5,.8, .6,.7,.2,.4,.4,.4,.5]),
('ELECTRICAL', 'Kỹ thuật điện', 'Kỹ thuật',
 'Thiết kế và vận hành hệ thống điện, điện tử và điều khiển.',
 'Người học tìm hiểu mạch điện, hệ thống điện, tự động hóa và năng lượng. Nền tảng toán và vật lý quan trọng.',
 ARRAY['A00','A01','D07'], ARRAY['Kỹ sư điện','Kỹ sư tự động hóa','Kỹ sư năng lượng tái tạo'],
 ARRAY[.9,.7,.1,.1,.2,.5, .9,.2,.6,.2,.4,.9, .6,.8,.2,.3,.4,.4,.5]),
('CIVIL', 'Kỹ thuật xây dựng', 'Kỹ thuật',
 'Thiết kế, thi công và giám sát các công trình xây dựng.',
 'Đào tạo về kết cấu, vật liệu, địa kỹ thuật và quản lý dự án xây dựng. Công việc gắn với công trường.',
 ARRAY['A00','A01','D07'], ARRAY['Kỹ sư xây dựng','Giám sát công trình','Quản lý dự án'],
 ARRAY[.9,.5,.2,.1,.3,.6, .7,.2,.9,.3,.5,.7, .6,.7,.2,.4,.4,.4,.7]),
('AUTOMOTIVE', 'Kỹ thuật ô tô', 'Kỹ thuật',
 'Thiết kế, chế tạo, kiểm định và bảo dưỡng ô tô.',
 'Đào tạo về động cơ, hệ thống truyền lực, điện - điện tử ô tô và xe điện.',
 ARRAY['A00','A01','D07'], ARRAY['Kỹ sư ô tô','Kỹ thuật viên chẩn đoán','Chuyên viên kỹ thuật dịch vụ'],
 ARRAY[1,.6,.1,.1,.3,.4, .7,.2,.8,.3,.4,.7, .6,.6,.1,.4,.5,.3,.6]),
('TOURISM', 'Du lịch - Khách sạn', 'Du lịch - Dịch vụ',
 'Tổ chức tour, vận hành khách sạn và dịch vụ du lịch.',
 'Người học tìm hiểu quản trị lữ hành, khách sạn, nhà hàng và chăm sóc khách hàng. Cần giao tiếp tốt, ngoại ngữ và tính linh hoạt.',
 ARRAY['A01','C00','D01','D14'], ARRAY['Hướng dẫn viên du lịch','Quản lý khách sạn','Điều hành tour'],
 ARRAY[.2,.2,.4,.8,.7,.4, .3,.8,.3,1,.5,.3, .5,.4,.5,.5,.4,.4,.8]);

-- Guard against a typo in the long lists above: every profile must have exactly one weight per dimension.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM seed_majors WHERE array_length(profile, 1) <> 19) THEN
        RAISE EXCEPTION 'every seed major needs exactly 19 profile weights';
    END IF;
    IF (SELECT count(*) FROM seed_majors) <> 30 THEN
        RAISE EXCEPTION 'expected 30 seed majors';
    END IF;
END $$;

INSERT INTO majors (code, name, group_name, short_description, description, combos, typical_jobs)
SELECT code, name, group_name, short_description, description, combos, typical_jobs FROM seed_majors;

INSERT INTO major_profiles (major_id, dimension_code, weight)
SELECT m.id, d.code, p.weight
FROM seed_majors s
JOIN majors m ON m.code = s.code
CROSS JOIN LATERAL unnest(s.profile) WITH ORDINALITY AS p(weight, pos)
JOIN (VALUES (1, 'R'), (2, 'I'), (3, 'A'), (4, 'S'), (5, 'E'), (6, 'C'),
             (7, 'LOGIC'), (8, 'VERBAL'), (9, 'SPATIAL'), (10, 'SOCIAL_SKILL'), (11, 'CREATIVE'), (12, 'NUMERIC'),
             (13, 'VAL_INCOME'), (14, 'VAL_STABILITY'), (15, 'VAL_HELPING'), (16, 'VAL_CREATIVITY'),
             (17, 'VAL_AUTONOMY'), (18, 'VAL_PRESTIGE'), (19, 'VAL_TEAMWORK')) AS d(pos, code) ON d.pos = p.pos
WHERE p.weight > 0;
