-- Seed: 8 SAMPLE universities and SAMPLE admission data.
--
-- !! EVERYTHING HERE IS INVENTED for development and demos. The university names are fictional and the cutoff
-- !! scores and tuition fees are generated by a deterministic formula. They are NOT real figures and must never be
-- !! shown to students as such. Rows are flagged is_sample = true and the API repeats that flag in its responses.
-- !! Replace them with real, sourced data (admin API or an import) before going live.

INSERT INTO universities (code, name, region, type, is_sample) VALUES
    ('UNI_N1', 'Đại học Mẫu Hà Nội (dữ liệu mẫu)', 'NORTH', 'PUBLIC', true),
    ('UNI_N2', 'Đại học Công nghệ Mẫu miền Bắc (dữ liệu mẫu)', 'NORTH', 'PUBLIC', true),
    ('UNI_N3', 'Đại học Tư thục Mẫu Hà Nội (dữ liệu mẫu)', 'NORTH', 'PRIVATE', true),
    ('UNI_C1', 'Đại học Mẫu Đà Nẵng (dữ liệu mẫu)', 'CENTRAL', 'PUBLIC', true),
    ('UNI_C2', 'Đại học Mẫu Huế (dữ liệu mẫu)', 'CENTRAL', 'PUBLIC', true),
    ('UNI_S1', 'Đại học Mẫu TP. Hồ Chí Minh (dữ liệu mẫu)', 'SOUTH', 'PUBLIC', true),
    ('UNI_S2', 'Đại học Tư thục Mẫu Sài Gòn (dữ liệu mẫu)', 'SOUTH', 'PRIVATE', true),
    ('UNI_S3', 'Đại học Quốc tế Mẫu (dữ liệu mẫu)', 'SOUTH', 'INTERNATIONAL', true);

-- Typical sample cutoff (out of 30) per major before the university adjustment.
CREATE TEMP TABLE seed_cutoffs (major_code TEXT, base_cutoff NUMERIC) ON COMMIT DROP;
INSERT INTO seed_cutoffs VALUES
    ('MEDICINE', 26), ('PHARMACY', 24), ('DS', 25), ('IT', 24.5), ('CYBERSEC', 24), ('FINANCE', 24), ('INTLECON', 24),
    ('LAW', 23), ('MARKETING', 23.5), ('ECOMMERCE', 23), ('PR', 23), ('ENGLISH', 23), ('BUSINESS', 22.5),
    ('ACCOUNTING', 22), ('JOURNALISM', 22), ('MULTIMEDIA', 22), ('ARCHITECTURE', 21), ('ELECTRICAL', 21),
    ('AUTOMOTIVE', 21), ('MECHANICAL', 20), ('LOGISTICS', 22), ('NURSING', 19), ('PSYCHOLOGY', 22), ('BIOTECH', 20),
    ('FOODTECH', 19), ('CIVIL', 18), ('EDUCATION', 21), ('SOCIALWORK', 17), ('TOURISM', 20), ('GRAPHICDESIGN', 21);

-- Adjustment of the cutoff and the yearly tuition by university.
CREATE TEMP TABLE seed_uni_params (uni_code TEXT, cutoff_adjust NUMERIC, tuition BIGINT) ON COMMIT DROP;
INSERT INTO seed_uni_params VALUES
    ('UNI_N1', 1.5, 24000000), ('UNI_N2', 1.0, 27000000), ('UNI_N3', -3.0, 42000000),
    ('UNI_C1', -1.5, 20000000), ('UNI_C2', -2.0, 18000000),
    ('UNI_S1', 1.5, 26000000), ('UNI_S2', -3.5, 48000000), ('UNI_S3', -1.5, 120000000);

-- UNI_N1 and UNI_S1 offer every major; the others offer about 55% of them (picked by a stable hash).
-- Three years of data (2023-2025) for the first exam combination of each major.
INSERT INTO university_majors (university_id, major_id, year, combo, cutoff_score, tuition_per_year, is_sample)
SELECT u.id, m.id, y.year, m.combos[1],
       LEAST(30, GREATEST(10, round(c.base_cutoff + p.cutoff_adjust
           + ((('x' || substr(md5(u.code || m.code || y.year::text), 1, 6))::bit(24)::int % 9) - 4) * 0.1, 2))),
       p.tuition + (y.year - 2023) * 1000000
           + ((('x' || substr(md5(m.code || u.code), 1, 6))::bit(24)::int % 5) * 500000),
       true
FROM universities u
JOIN seed_uni_params p ON p.uni_code = u.code
CROSS JOIN majors m
JOIN seed_cutoffs c ON c.major_code = m.code
CROSS JOIN (VALUES (2023), (2024), (2025)) AS y(year)
WHERE u.code IN ('UNI_N1', 'UNI_S1')
   OR (('x' || substr(md5(u.code || m.code), 1, 6))::bit(24)::int % 100) < 55;
