package vn.career.common.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

/** Central catalogue of API error codes. Every code knows the HTTP status it is returned with. */
@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    // 400
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    MALFORMED_REQUEST(HttpStatus.BAD_REQUEST),

    // 401
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
    TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    REFRESH_TOKEN_INVALID(HttpStatus.UNAUTHORIZED),

    // 403
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    ACCOUNT_LOCKED(HttpStatus.FORBIDDEN),
    CONSENT_REQUIRED(HttpStatus.FORBIDDEN),
    MENTOR_NOT_VERIFIED(HttpStatus.FORBIDDEN),

    // 404
    NOT_FOUND(HttpStatus.NOT_FOUND),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVITE_NOT_FOUND(HttpStatus.NOT_FOUND),
    SURVEY_NOT_FOUND(HttpStatus.NOT_FOUND),
    SECTION_NOT_FOUND(HttpStatus.NOT_FOUND),
    QUESTION_NOT_FOUND(HttpStatus.NOT_FOUND),
    ATTEMPT_NOT_FOUND(HttpStatus.NOT_FOUND),
    NO_ACTIVE_SURVEY(HttpStatus.NOT_FOUND),
    MAJOR_NOT_FOUND(HttpStatus.NOT_FOUND),
    UNIVERSITY_NOT_FOUND(HttpStatus.NOT_FOUND),
    UNIVERSITY_MAJOR_NOT_FOUND(HttpStatus.NOT_FOUND),
    POV_NOT_FOUND(HttpStatus.NOT_FOUND),
    MENTOR_NOT_FOUND(HttpStatus.NOT_FOUND),
    THREAD_NOT_FOUND(HttpStatus.NOT_FOUND),
    ANSWER_NOT_FOUND(HttpStatus.NOT_FOUND),
    CONVERSATION_NOT_FOUND(HttpStatus.NOT_FOUND),

    // 405 / 415
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
    UNSUPPORTED_MEDIA_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE),

    // 422 business rules
    BUSINESS_RULE_VIOLATION(HttpStatus.UNPROCESSABLE_ENTITY),
    EMAIL_ALREADY_EXISTS(HttpStatus.UNPROCESSABLE_ENTITY),
    ROLE_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY),
    INVITE_ALREADY_USED(HttpStatus.UNPROCESSABLE_ENTITY),
    INVITE_EXPIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    ALREADY_LINKED(HttpStatus.UNPROCESSABLE_ENTITY),
    SURVEY_NOT_EDITABLE(HttpStatus.UNPROCESSABLE_ENTITY),
    SURVEY_NOT_PUBLISHABLE(HttpStatus.UNPROCESSABLE_ENTITY),
    ATTEMPT_NOT_EDITABLE(HttpStatus.UNPROCESSABLE_ENTITY),
    DUPLICATE_ORDER_INDEX(HttpStatus.UNPROCESSABLE_ENTITY),
    DUPLICATE_SECTION_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    SURVEY_INCOMPLETE(HttpStatus.UNPROCESSABLE_ENTITY),
    RESULT_NOT_READY(HttpStatus.UNPROCESSABLE_ENTITY),
    DUPLICATE_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    POV_NOT_EDITABLE(HttpStatus.UNPROCESSABLE_ENTITY),
    POV_INVALID_STATE(HttpStatus.UNPROCESSABLE_ENTITY),
    MENTOR_ALREADY_APPLIED(HttpStatus.UNPROCESSABLE_ENTITY),
    ACCOUNT_DELETE_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY),

    // 429
    TOO_MANY_LOGIN_ATTEMPTS(HttpStatus.TOO_MANY_REQUESTS),
    TOO_MANY_REQUESTS(HttpStatus.TOO_MANY_REQUESTS),

    // 500 / 503
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE);

    private final HttpStatus status;
}
